### ISSUE TITLE
abundance_difference

### ISSUE THREAD

**Issue by mavolio** [NCEAS/codyn#105]
Hey @itcarroll abundance_change looks great and works perfectly. 

Unfortunately, I can't get abundance difference to work. It tells me reference.treatment is an unused argument...

> test<-abundance_difference(df = pplots, time.var = "year", species.var = "species", abundance.var = "relative_cover", replicate.var = "plot", treatment.var = "treatment", reference.treatment = "N1P0")

Error in (function (df, time.var = NULL, species.var, abundance.var, replicate.var = NULL,  : 
  unused argument (reference.treatment = "N1P0").

Thoughts?

**Comment by itcarroll** [comment]
Fixed in 054cf96.
