### ISSUE TITLE
problem with reference.time

### ISSUE THREAD

**Issue by mavolio** [NCEAS/codyn#109]
test<-subset(codyndat_clean, site_project_comm =="OND.ZOOPS.0")
testing<-RAC_change(df = test, time.var = "experiment_year", species.var = "species", abundance.var = "abundance", replicate.var = "id", reference.time = 1976.429)

get this error: Error in `[<-.data.frame`(`*tmp*`, idx, abundance.var, value = 0) : 
  replacement has 1 row, data has 0

**Comment by itcarroll** [comment]
This isn't an error, but it's maybe undesired. The problem is the 'experiment_year' is a numeric type so more precision is required to get the reference correct:

```
testing <- RAC_change(
  df = test, time.var = "experiment_year", species.var = "species", 
  abundance.var = "abundance", replicate.var = "id", 
  reference.time = 1976.428767)
```

Beyond following through with #108, I'm not sure there's anything to do.

**Comment by itcarroll** [comment]
@mavolio Close if you agree.

**Comment by mavolio** [comment]
I agree
