### ISSUE TITLE
Time analysis not with years but with dates

### ISSUE THREAD

**Issue by JessicaGarzke** [NCEAS/codyn#114]
Hello,
I am new using codyn but I think that this is great to analyse my timeseries data for phytoplankton.  I want to use sampling dates "d-m-Y" to analyse species turnover, rank shifts, community stability between the sampling dates. I tried to do that but because I don't use years I get an error.  Is it possible to compare between dates and not only years?

**Comment by mavolio** [comment]
Hi Jessica,

You should be able to use any time period with codyn, hours, days, years.... I wonder if it is a problem with the format of the time column. Can you try formatting the time column as numeric? Or can you make a dummy time column numbered 1 through X and feed that column into the function. You could then merge back to the original dates.

Please let me know if this doesn't work.

Meghan

**Comment by JessicaGarzke** [comment]
Hi Meghan,
I created a dummy year for each sampling date. But now I get the following error 

Error in check_single_onerep(df, time.var, species.var) : Either data span multiple replicates with no replicate.var specified or multiple records within years for some species

when using the turnover function. But I don't have replicates. I can send you my dataset if you want to have a look at it (in a private message). But in general I have a few hundred sampling dates in one column, and for each sampling date several phytoplankton species. I want to calculate the turnover and such over the oservation time comparing one sampling date to the other.

**Comment by laurenmh** [comment]
Hi Meghan,

I just sent Jessica some thoughts, below.

Best,

Lauren

It sounds to me like you have at least one date that has 2 or more rows for the same species. I would do a quick check for any redundancy (maybe through a repeated entry error?). I'm assuming you are using the sampling date and not year for the time.var? I might convert sampling date to a decimal date to make sure it runs in order.

On Mar 4, 2020, at 11:13 AM, JessicaGarzke <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Meghan,
I created a dummy year for each sampling date. But now I get the following error

Error in check_single_onerep(df, time.var, species.var) : Either data span multiple replicates with no replicate.var specified or multiple records within years for some species

when using the turnover function. But I don't have replicates. I can send you my dataset if you want to have a look at it (in a private message). But in general I have a few hundred sampling dates in one column, and for each sampling date several phytoplankton species. I want to calculate the turnover and such over the oservation time comparing one sampling date to the other.

**Comment by mbjones** [comment]
Looks like this issue was resolved through discussion with @laurenmh and @mavolio, so closing. Please reopen if further discussion is needed.
