### ISSUE TITLE
update codyn for R 4.0

### ISSUE THREAD

**Issue by mbjones** [NCEAS/codyn#115]
CRAN notified me of breaking changes that require use to explicitly set `stringsAsFactors` in R code, which will break in the upcoming R 4.x releases.

**Comment by itcarroll** [comment]
Fixed in #118, for release with codyn 2.0.4.

**Comment by mbjones** [comment]
Thanks @itcarroll ! Really appreciated.  I'll get this submitted this week to CRAN.
