### ISSUE TITLE
update cran-comments, description, and version for 2.0.4

### ISSUE THREAD

**Issue by mbjones** [NCEAS/codyn#116]
Prepare the 2.0.4 release.

**Comment by itcarroll** [comment]
@mbjones Testing on all platforms, for cran-comments.md reporting, is looking to be a pain. R-hub only has 3.x R on Ubuntu, the docker containers are dying on a LaTeX dependency, and Travis is testing R 4.x but on Ubuntu 16 LTS ... So, how do we get this tiny change through most easily?

**Comment by mbjones** [comment]
Yeah, that’s what I had trouble with too, getting testing working on rhub on the right versions. I have a configurable docker script in the repo that can also run the checks so my next step was going to be to try that. But I’m surprised rhub isn’t working now that r 4 is out. I’ll try later tonight.

**Comment by mbjones** [comment]
@itcarroll FYI, I updated a bunch of stuff, and tracked down the build error on rhub to not being able to install `pillar`, which then impacts `ggplot2` and the building of vignettes.  This is only a development requirement.  Others seem to have problems with `pillar` installing properly in various locations. I'll keep plugging at what is up with that, although I think it will have no impact on codyn checks once it is installed.

**Comment by mbjones** [comment]
Also, working on the `develop` branch, following the new guidelines I posted in CONTRIBUTING.md.

**Comment by mbjones** [comment]
Got the checks working on a variety of platforms, documented in cran-comments. Merged to master, and submitted to CRAN. We'll see how it fares on their automated tests. Hopefully we'll get good news tomorrow, and I will come back and tag the release.

TODO:

- [ ] Tag 2.0.4 release

**Comment by mbjones** [comment]
The new package was now accepted on CRAN so tagging the release.

https://cran.rstudio.com/web/packages/codyn/index.html
