### ISSUE TITLE
Installation error: package 'codyn' is not available (for R version 3.6.2)

### ISSUE THREAD

**Issue by mcrossley3** [NCEAS/codyn#117]
I get the following error message when I attempt:

>install.packages('codyn')

package 'codyn' is not available (for R version 3.6.2)

Do you have any suggestions for how to get this package up and running on my machine?

**Comment by itcarroll** [comment]
Thanks for the report. While we work to get the package back up on CRAN, you can still use it by installing directly from GitHub:

```
library(devtools)
install_github("NCEAS/codyn")
```

**Comment by itcarroll** [comment]
Fixed in #118, for release with codyn 2.0.4.
