### ISSUE TITLE
new release for R R version 3.6.3 or above?

### ISSUE THREAD

**Issue by Gian77** [NCEAS/codyn#119]
Hello, I was wondering when a new package release for R  3.6.3 or above will available. 
Thank you,
Gian

**Comment by mbjones** [comment]
@Gian77 The R 4.0 release introduced incompatibilities that caused the package to be archived and are now being resolved - a fix was just proposed in issue #115.  It will be back on CRAN relatively soon.  In the meantime, you can still install `codyn` for R 3.6.* from GitHub:

```r
remotes::install_github("NCEAS/codyn")
```

**Comment by Gian77** [comment]
Awesome! Thanks a lot, it worked.
