### ISSUE TITLE
add paper ref to DESCRIPTION

### ISSUE THREAD

**Issue by mbjones** [NCEAS/codyn#120]
Uwe Ligges at CRAN requested that, if we have a reference for our methodological approach, we add it to our DESCRIPTION:

> Thanks, on its way to CRAN.
>
>For the future: Is there some reference about the method you can add in the Description field in the form Authors (year) <doi:.....>?
>
> Best,
> Uwe Ligges

I responded that we could add Hallett et al. 2016 on our next release.

Hallett et al. (2016) codyn: An R package of community dynamics metrics. Methods in Ecology and Evolution. http://doi.org/10.1111/2041-210X.12569

**Comment by mbjones** [comment]
Ready for release, committed to `develop` branch for the next time that a release comes out.  Currently targeting the 2.1.0 milestone, but can get packaged with whatever release is next.

**Comment by mavolio** [comment]
Hi Matt,

Can we add two reference papers? My ecosphere 2019 paper details the other
half of the functions that are not in Lauren's paper.

Meghan

**Comment by mbjones** [comment]
Absolutely.  Feel free to add it to both the README.md and DESCRIPTION file in the `develop` branch and it will get included in the next release.  It would be nice to have them both in the README.md.

**Comment by mbjones** [comment]
Added both papers to README and DESCRIPTION.

See sha 440cd9f476a1aa5bbeef9bb0f803e21933bfd468
