### ISSUE TITLE
replicate column and mutiple records error message

### ISSUE THREAD

**Issue by adrianacravo** [NCEAS/codyn#121]
Hi,
first of all I would like to thank all the contributors for the package! I was looking for something like that to describe my community composition through time and it arrived right on time! :D 
I've been trying to do the analysis with the package, but I think I didn't understand that well the role of the "replicate" column. I tried to plot the data attached and in the _replicate_ column, I specified the name of sample where each Family came from, that's why I have many rows with the same name (under the replicate column). Usually, I have 5 samples per lake per season, and some lakes appear again in another season or another year. Since the samples taken from the same lake are pseudo replicates, that was another reason to add the replicate column and indicate their IDs. However, when I try to run the _turnover_ command, I get the error message: 

`turnover.sumfam <- turnover(df = Rt_all_f,  
                       time.var = "season",  
                       species.var = "family", 
                       abundance.var = "abundance",
                       replicate.var = "replicate")`

`Error in check_single(df, time.var, species.var, replicate.var) : 
  Multiple records for one or more species found at:
 family                          replicate   
 "Acetobacteraceae"              "AY2017-1-1"
 "Aeromonadaceae"                "AY2017-1-1"
 "Akkermansiaceae"               "AY2017-1-1"
 "Bacillaceae"                   "AY2017-1-1"
 "Barnesiellaceae"               "AY2017-1-1"
 "Beijerinckiaceae"              "AY2017-1-1"
 "Burkholderiaceae"              "AY2017-1-1"
 "Chitinophagaceae"              "AY2017-1-1"
 "Christensenellaceae"           "AY2017-1-1"
 "Clostridiaceae 1"              "AY2017-1-1"
 "Clostridiales vadinBB60 group" "AY2017-1-1"
 "Cyanobiaceae"                  "AY2017-1-1"
 "Deferribacteraceae"            "AY2017-1-1"
 "Desulfovibrionaceae"           "AY2017-1-1"
 "Enterobacteriaceae"            "AY2017-1-1"
 "Flavobacteriaceae"             "AY2017-1-1"
 "Lachnospiraceae"               "AY2017-1-1"
 "Leptolyngbyaceae"              "AY2017-1-1"
 "Magnetospirillaceae"           "AY2017-1-1"`

It says that my replicates are repeated,  but I thought that was exactly the reason for the _replicate.var_ option. I already had this issue before, but when I was not considering any replicate option. So now I'm not sure if I understand what should go in the _replicate_ option, since I cannot repeat any name there. 
Could someone give me a light, here, please?

Thanks a lot!!!
Adriana

[Rt_all_30Fam3.txt](https://github.com/NCEAS/codyn/files/4717946/Rt_all_30Fam3.txt)

**Comment by mbjones** [comment]
HI @adrianacravo It's hard to diagnose without a [reproducible example](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) (and see [reprex](https://reprex.tidyverse.org/) and ), but 
I suspect that its a simple misunderstanding about the details of the `replicate.var` variable. In this case, the replicate.var is meant to uniquely identify the replicates in the set for a given taxon group. The [R help for `turnover`](https://www.rdocumentation.org/packages/codyn/versions/2.0.4/topics/turnover) says:

```
If multiple replicates are included in the data frame, that column should be specified 
with replicate.var. Each replicate should reflect a single experimental unit - there 
must be a single abundance value per species within each time point and replicate.
```

In your case, it appears that, for a given species and time value, the value for replicate is repeating. I suspect that is the issue. But if you can confirm that every time-species-replicate combination of values is unique, then there might be an issue to explore. If so, please provide a reproducible example. Good luck!

**Comment by adrianacravo** [comment]
Hi, @mbjones, actually it was a lack of attention from my side. I wrote the same replication ID twice for the same factors, now I fixed it and didn't have the same problem, thanks!! 
However, now when I run the code
`turnover <- turnover(df = test_c,  
                       time.var = "season",  
                       species.var = "family", 
                       abundance.var = "abundance", replicate.var = "replicate")`

I get this new problem
`Error in mapply(FUN = f, ..., SIMPLIFY = FALSE) : zero-length inputs cannot be mixed with those of non-zero length`

I attached here ( [piece_of_data.txt](https://github.com/NCEAS/codyn/files/4723416/piece_of_data.txt) ) part of my data that I used for the analysis, as an example. I restarted the session, loaded the library once again and checked the same question on google, but still could not find the solution. When I delete the column _replicate_ from the data and sum up the abundances (combining the replicates taken from the same place into just one), I don't have this problem and the function works fine, but that's not the best way to analyse the data. 
Sorry to insist on this, but I could not fix it so far. I hope the example data I sent here is enough!

Thanks a lot once again for the feedback

**Comment by mbjones** [comment]
Looking at your sample data, I think the problem arises because there are sometimes only a single time period in `season` when we split by `replicate.var`. Turnover can only be calculated if there are multiple time periods represented in a replicate. Maybe this is an artifact of how you have coded your replicates -- in which case, simply make sure that repeated measures of the same replicate across seasons use the same replicate value.

**Comment by adrianacravo** [comment]
hi, @mbjones , 
thanks! I could solve the problem, it was indeed a problem with my replicates code! 
I appreciate the help :)
