### ISSUE TITLE
codyn 2.0.4 failing CRAN checks

### ISSUE THREAD

**Issue by mbjones** [NCEAS/codyn#122]
The current codyn CRAN release (2.0.4) has started failing CRAN checks for some reason. See: https://cran.r-project.org/web/checks/check_results_codyn.html

The CRAN maintainers wrote and said:

```
Please correct before 2020-12-08 to safely retain your package on CRAN.
```

Any help on maintenance would be appreciated @laurenmh @itcarroll @mavolio . I haven't looked into what is failing and why. Thanks!

**Comment by mbjones** [comment]
I ran the checks without error under RHub using R-devel:

  - fedora-clang-devel: R Under development (unstable) (2020-10-24 r79367) (x86_64-pc-linux-gnu (64-bit)) 
  - fedora-gcc-devel:  R Under development (unstable) (2020-10-24 r79367) (x86_64-pc-linux-gnu (64-bit))

Both passed without a problem, but RHub is for some reason using `r79367` of R-devel, whereas the CRAN check page output is using `R Under development (unstable) (2020-11-23 r79474)`, so I need to figure out how to get RHub to use the most recent R-devel release -- that will likely reproduce the issue. The RHub build grabs the most recent R-devel from subversion, so I am perplexed why it didn't grab something more recent.

**Comment by gaborcsardi** [comment]
The images are updated on every weekend.

**Comment by itcarroll** [comment]
Appears there is an upcoming change to `get` that changes behavior to [raise an error](https://developer.r-project.org/blosxom.cgi/R-devel/2020/11/24#n2020-11-24). Based on the CRAN check results, this is likely the cause of our error. Investigating under r-devel presently.
