### ISSUE TITLE
prep release for 2.0.5

### ISSUE THREAD

**Issue by mbjones** [NCEAS/codyn#124]
- [x] merge any outstanding feature branches to `develop`
- [x] close any issues assigned to this release
- [x] check and update contributors list and update DESCRIPTION/CITATION if needed
    - [x] Include ORCID identifiers if possible
- [x] Update version number, publish date, etc. in DESCRIPTION
- [x] check that all new functions have unit tests
- [x] update NEWS
- [x] update cran_comments
- [x] test with testthat
- [x] run revdepcheck::revdep_check()
- [x] devtools::check()
   - [x] macOS R R-release
   - [x] Windows (via win-builder): x86_64-w64-mingw32 (64-bit) R-release (4.0.3)
   - [x] Windows (via win-builder): x86_64-w64-mingw32 (64-bit) R-oldrelease (3.6.3)
   - [x] Windows (via win-builder):  x86_64-w64-mingw32 (64-bit)  R Under development (unstable) (4.1.0)
- [x] rhub::check_for_cran()
   - [x] Fedora Linux, R-devel, clang, gfortran: fedora-clang-devel
   - [x] Fedora Linux, R-devel, GCC: fedora-gcc-devel
   - [x] Ubuntu Linux, R-devel, GCC: ubuntu-gcc-devel
- [x] run spell_check()
- [x] merge`develop` to `main` branch in prep for release
- [x] confirm build is working on Travis https://travis-ci.com/NCEAS/codyn
- [x] run devtools::release() on `main` branch

After release is posted by CRAN:
- [x] create release tag

**Comment by mbjones** [comment]
I was unable to find ORCID ids for Ian and Sydney. While several entries exist for each, there was insufficient public info to differentiate them and figure out which are the correct ORCIDs. @itcarroll Do you have one that you can provide?

**Comment by itcarroll** [comment]
https://orcid.org/0000-0002-3616-810X

**Comment by mbjones** [comment]
Thanks, I updated your ORCID. I got the build working on Travis.com and r-hub, and merged the `develop` branch to `master`. Submitted to CRAN for review on 2020-11-30 at 6:20 pm AK time. Awaiting feedback.

**Comment by mbjones** [comment]
Release 2.0.5 is complete, tagged, and accepted at CRAN. Builds for fedora and other platforms looking good. Thanks @itcarroll 

https://cran.rstudio.com/web/checks/check_results_codyn.html
