### ISSUE TITLE
Dealing with multiple ASV classified as unknown

### ISSUE THREAD

**Issue by pulidofabs** [NCEAS/codyn#125]
Hello, 

I am attempting to use the Codyn package to calculate the turnover rates of fungal ASVs. However, I have multiple genera belonging to different orders that are classified as unknown and I am unsure how I can go about dealing with this issue. 

**When I try to run the code, I receive the following error:** 
"Error in check_single(df, time.var, species.var, replicate.var) : Multiple records for one or more species found at: Genus  "unidentified"  and Treatment. 
    
If you could please let me know how I can deal with this, I would really appreciate it.

**Comment by mbjones** [comment]
Without a specific code and data example, I can't really help. But, based on the error, it seems you need to resolve the multiple "Unidentified" classifications, possibly by coding them differently in each group. A reproducible example would be needed to narrow down the problem further.
