### ISSUE TITLE
synchrony.R; metric = "Gross" producing different synchrony measures than expected

### ISSUE THREAD

**Issue by gsrednick** [NCEAS/codyn#130]
I have been working with the synchrony "Gross" function and have found that synchrony measures produced differ from manual calculations of Gross-synchrony (Gross et al. 2014). I have written my manual calculations to be as similar as possible to those in the synchrony.R/synch_onerep function. I cannot seem to locate where these calculations diverge in the synchrony.R source code. Any thoughts on why this might be?

See below:

```
set.seed(42)
df <- data.frame(year = rep(1:6,each = 4),species=rep(LETTERS[1:4],6),cover=sample(5:32,24))

## my calculations
df_wide <- df %>%
  dplyr::select(year, species, cover) %>%
  tidyr::spread(species, cover, fill = 0)

sums <- rowSums(df_wide[-1])

com_cor<-stats::cor(df_wide[2:5],sums)

my_sync<-mean(com_cor)

# [1] 0.3135837

## codyn
synchrony(df,
          time.var = "year",
          species.var = "species",
          abundance.var = "cover",
          metric = "Gross")

# [1] -0.4150936
```

**Comment by mbjones** [comment]
Thanks for the report, @gsrednick. Nothing jumps out at me immediately.

One way to track this down would be to 1) save the intermediate results of your calculations in variables, and 2) use the R debugger to step through the synch_onerep to find the intermediate results as that progresses, and compare them as you go to see where they diverge. If you do find a bug, please let us know and we'll be happy to incorporate a fix.

**Comment by gsrednick** [comment]
Thanks for the tip @mbjones! Debugging was very helpful and found the issue: when performing correlations for each species abundance and the total abundance of the **rest** of the species I was mistakenly using the total abundance of **all** species. Apparently I glazed over this bit in Gross et al. (2014 AmNat). Disaster averted. Thanks for your time.
