### ISSUE TITLE
choose good names for new functions

### ISSUE THREAD

**Issue by mbjones** [NCEAS/codyn#79]
@mavolio proposed the following new functions:

S, E_q, SERGL_func, calculate_Mult_change, calculate_Curve_Change, SERSp_func, calculate_Mult_diff, calculate_curve_diff

Need to discuss and rename consistently with `codyn` approaches.

**Comment by itcarroll** [comment]
Function names in #83 are as follows:

- [ ] multivariate_change
- [ ] multivariate_change
- [ ] multivariate_change
