### ISSUE TITLE
prepare 2.0.0 for CRAN release

### ISSUE THREAD

**Issue by mbjones** [NCEAS/codyn#81]
Update NEWS, REAMDE, DESCRIPTION, etc.

**Comment by itcarroll** [comment]
Reminder that ticket #84 has a discussion about version numbers. Meghan and I think the next release should be 2.0.

**Comment by mbjones** [comment]
Bummer that the second release is already incompatible, but it sounds like everyone agrees that is the right path.  Have @laurenmh and others from the team weighed in on the incompatibility issue?  If so, I can update the version # in the release process.

**Comment by mbjones** [comment]
Cleaned up package, got tests and checks running locally on MacOS and via docker on Linux, plus via winbuilder.  All R CMD checks are now passing.  Package is ready for final review before submission to CRAN.

**Comment by mbjones** [comment]
CRAN approved and tagged the release.
