### ISSUE TITLE
update codyn-package.R for new release

### ISSUE THREAD

**Issue by mbjones** [NCEAS/codyn#85]
Package documentation needs to be updated with new functions and descriptions, etc.

**Comment by mavolio** [comment]
Look in the R folder for the codyn.package and update this file.

**Comment by mavolio** [comment]
@mbjones this update requires a whole new package description. Is there a way to do this so I am not overwriting what as been written, but instead saying in the new update the following as been added?

**Comment by mavolio** [comment]
I rewrote the package description.
