### ISSUE TITLE
community_structure won't give multiple evenness metrics in output

### ISSUE THREAD

**Issue by klapierre** [NCEAS/codyn#87]
The function sample code shows you can say metric=c('EQ', 'Evar', 'SimpsonEvenness').  But when I do this, I just get Evar back (default). Either make it so you can get all three back (ideal) or change the sample code so you only show one. (note, the examples at the bottom don't show you can have all three, so maybe you can't?)

**Comment by klapierre** [comment]
Same with community_diversity function for Shannon's and Inverse Simpson's.

**Comment by mbjones** [comment]
@mavolio can you also test the input to be sure the user has provided only one, and if not provide a useful error message?

**Comment by mavolio** [comment]
this is repetitive with sally's issue #96
