### ISSUE TITLE
error for more than one species in curve_change function has typos

### ISSUE THREAD

**Issue by klapierre** [NCEAS/codyn#88]
Error in check_single(df, time.var, species.var, replicate.var) : 
  For the following replicates in the following time points, there are more than one records for species

should be as follows:
For the following replicates at the following time points, there is more than one record for species

**Comment by mavolio** [comment]
changes in utilities check_single

**Comment by itcarroll** [comment]
@mavolio Would be good form to push commit that references this issue to the RACs_paper_functions branch when/before closing.

**Comment by mavolio** [comment]
Huh? I changed this in mavolio/codyn - RACs_paper_function and closed the
issue on nceas/codyn.
I am not sure I understand this.

**Comment by itcarroll** [comment]
Pushes to RACs_paper_functions that include #x will be noted in issue x on
NCEAS/codyn, because pull request. It is not a terribly brilliant design,
but that's how it works.

--
Ian Carroll | carroll.ian@gmail.com | 805-291-7933
