### ISSUE TITLE
curve difference error for pooling needs better explanation

### ISSUE THREAD

**Issue by klapierre** [NCEAS/codyn#89]
Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index

What does this error mean?  Better error message needed.

**Comment by klapierre** [comment]
Same with RAC difference.

**Comment by klapierre** [comment]
It is now clear to me that the error should instead say "treatment.var not specified"

**Comment by klapierre** [comment]
Here's my code that generated the error:

curveDifference <- curve_difference(data, time.var='calendar_year', species.var='genus_species', abundance.var='cover', replicate.var='plot_id', pool=T)


And here's the code that fixed the error:

curveDifference <- curve_difference(data, time.var='calendar_year', species.var='genus_species', abundance.var='cover', replicate.var='plot_id', treatment.var='treatment', pool=T)



So the problem was my own user error that I didn't specify a treatment column.  But the error message could be more intuitive and just tell me to put in a treatment column.  I like Matt's suggestion to have some check on the function that all necessary parts were input and give an error if not.

**Comment by mavolio** [comment]
add a check to the function that if pool or block are specified, then treatment also has to be speficied

**Comment by itcarroll** [comment]
Combine with work on testing that just one metric has been specified (#96).
