### ISSUE TITLE
abundance_difference function help typos

### ISSUE THREAD

**Issue by klapierre** [NCEAS/codyn#92]
(a) first abundance in description spelled wrong.
 
(b)
under Arguments -- pool: 
you write the following:
The default value is "FALSE", a value of "TRUE" averages abundance of each species within a treatment at a given time point.

rephrase to be:
The default value is "FALSE", a value of "TRUE" averages the abundances of each species within a treatment at a given time point.

(c)
under Values -- difference
positive is spelled wrong

**Comment by mavolio** [comment]
corrected the typos
