### ISSUE TITLE
wishing and hoping for addition of comparison to a single trt or timepoint

### ISSUE THREAD

**Issue by klapierre** [NCEAS/codyn#93]
Wouldn't it be nice if you could specify just one treatment or just one time point in the functions?  Like I tell you, just give me output where treatment2='control', and you do it for me.  That way I don't have to subset it myself later.  This could be an optional thing, and the default could be to get all pairwise comparisons, which is also nice.

**Comment by mavolio** [comment]
@itcarroll @mbjones how difficult would it be to do this? If this will take a lot of work, I prefer to not do this and think this is something we can do on a future update (or never). But it is is fairly easy, many people have told me they would like to easily specify comparing all changes to year 1, for example.

**Comment by mbjones** [comment]
If I understand the request, I think it would be fairly straightforward if its a simple filter operation.  I would implement it as an optional additional parameter at the end of each of the methods.  If the parameter is omitted, then just continue as we do now.  If it is provided, then use it to filter the input before calculating the metric.  I think the challenge is deciding how to provide filter conditions -- would people always want to filter on a `treatment2` variable, or would each case be different?  And would people want to apply multiple filters, such as `treatment2='nitrogen' AND treatment3='phosphorus'`?  If so, it might be better to just leave the filtering to a data preparation step where people can use convenient tools like dplyr that have lots of power and flexibility.  We certainly don't want to be going down the path of reimplementing filtering tools.

**Comment by mavolio** [comment]
For the difference functions:
Originally, the *_difference functions were all comparing a treatment to the control. feed back from co-authors then said that they want all treatments compared to one-another, hence the version we have now. I coded this as a loop, which of course is bad. Filtering the input wouldn't work because you still want all the input, you just do not want all the comparisons.  We could filter the output for the user, but that doesn't help save on time and a problem with these functions is that they take so long to run.

For the change functions:
As written, all of these compare each pair of consecutive years. Several co-authors have expressed the desire to have the option to do consecutive comparisons (as we do now) OR to compare everything to the first year of data. For this, no amount of filtering will fix what we have, it is an entirely new way to compare the data.

To me the similarity between these is the desire to have a reference to compare to, either time for the change functions or a treatment for the difference functions.

**Comment by mbjones** [comment]
@mavolio wrote: 
>  We could filter the output for the user, but that doesn't help save on time and a problem with these functions is that they take so long to run.

So, this sounds like the filter parameter would need to be applied in the loop to decide which comparisons to run, which would skip unwanted comparisons, saving time and reducing the output.  I still wonder how these would be specified.  Would it be applied to one of the core parameters specified in `time.var`, `species.var`, `abundance.var`, or `replicate.var`?

**Comment by itcarroll** [comment]
Every difference or change function includes a line something like 

    cross <- merge(x, y, by = species.var, suffixes = c('', '2'))

to create a cartesian product on whatever variable is being compared (usually time.var or treatment.var). Right after that, some logical test based on ordering (e.g. control < treatment_a < treatment_b) is used to eliminate unwanted comparisons. I *think* it would be easy to replace that with a requirement for a specific value for time.var or treatment.var whenever some additional argument is provided. Perhaps "target" would be the argument name, defaulting to NULL.

Unfortunately, would probably be more efficient to have the necessary "if else" outside the split_apply_combine call ... which is precisely why I shouldn't have used an anonymous function for the FUN argument!

**Comment by itcarroll** [comment]
Add "reference.year" and "reference.treatment" for change and difference functions, respectively.

**Comment by itcarroll** [comment]
- [ ] RAC_change
- [ ] curve_change 
- [ ] abundance_change
- [ ] multivariate_change
- [ ] RAC_difference
- [ ] curve_difference
- [ ] abundance_difference
- [ ] multivariate_difference

Momentarilly stumped on multivariate_* as the mechanism for pairing replicates is not like the others.

**Comment by mavolio** [comment]
Hey, I think I know how to do multivariate. I think it would be at the end to subset the final dataset to only look at the relevant comparisons. Not ideal, as it is  still running for all the data, but would work. The only problem is that I think the reference would then be in time and time2 or treatment and treatment2. How big of a problem do you think that is?

**Comment by itcarroll** [comment]
Basically that, since vegan doesn't give us the option of comparing against a reference. I think I did it pretty sneaky, but you better write some manual tests.
