### ISSUE TITLE
Context Dependency of Compostion_Change & Composition_Dispersion

### ISSUE THREAD

**Issue by SallyKoerner** [NCEAS/codyn#94]
OK, composition change and dispersion are dependent on how many years you put? Well are they not also dependent on how many plots you put in within a year? I don't understand why you wouldn't want ALL the plots (treatments, years) for everything you wanted to compare in one calculation. For example if I wanted to compare the composition change for control plots vs trt plots wouldn't all those centroids have to be calculated at the same time in order to be able to say that one changed more than another?

**Comment by mavolio** [comment]
I have looked into this for the Change metrics and previously Kevin looked into it for the difference metrics. The output is slightly different depending on which replicates are included in the analysis, as we state in the help file. However, the patterns are qualitatively the same and we conclude are comparable.
attached are two documents that detail what we investigated.
[centroid_distances_19March2018.docx](https://github.com/NCEAS/codyn/files/1991653/centroid_distances_19March2018.docx)
[Multivariate change.docx](https://github.com/NCEAS/codyn/files/1991654/Multivariate.change.docx)
