### ISSUE TITLE
wish for multiple measure of evenness at once in community_structure

### ISSUE THREAD

**Issue by SallyKoerner** [NCEAS/codyn#96]
Is there a way to get multiple measures of evenness at once in community_structure, why to I have to pick just one?

And if you can already do this, could you add an example in the help file

**Comment by SallyKoerner** [comment]
same thing with diversity

Also in the help files from community_diversity the usage puts in c("Shannon", "InverseSimpson") but if I did that I got an error. So I am assuming you have to pick one or the other.

AND species.var is listed in the help file under arguments - but if I put in species.var in my code and specify that column then I get this error:
Error in community_diversity(ramps3, time.var = "year", replicate.var = "uniqueID",  : 
  unused argument (species.var = "species")
Your example code never specifies species.var column name. This is a little bit confusing. Is there any instance where you would need this? If not, maybe just delete it. or say somewhere that you need a species name column but that you dont code it in?

**Comment by mavolio** [comment]
we are going to check that the user has input only 1 metric, and better clarify the help file that you must choose 1 evenness of diversity metric
