### ISSUE TITLE
Community_structure and community_diversity wish

### ISSUE THREAD

**Issue by SallyKoerner** [NCEAS/codyn#97]
Is there a way to keep more columns when you run the community_structure function? For example my out put has a replicate column and a year but there is no treatment column, so now it is difficult to take the average richness of my different trtxyr which is what I really want in the end.

If there isn't a way, could you add it in?
And if there is, could you add the code to the examples?

thanks

**Comment by mavolio** [comment]
we will test that the user has only input 1 function. and better specify in the help file that you have to choose one.

**Comment by itcarroll** [comment]
If this is going to be implemented, it should be replicated across more than just the community_* functions.

**Comment by itcarroll** [comment]
We have decided not to implement this feature. Functions in `codyn` that aggregate the input dataset in some way (most do) would have to guess at the proper treatment of extraneous columns containing possibly non-identical values within a group. It's safer to let the user merge our output with their additional data.
